name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  AWS_ENDPOINT: "https://fake.com"
  AWS_REGION: "us-east-005"
  AWS_KEY_ID: "123"
  AWS_SECRET_ACCESS_KEY: "123"
  AWS_BUCKET_NAME: "123"
  NEXTAUTH_URL: "http://localhost:3000/"
  NEXTAUTH_SECRET: "5feaf48"
  GOOGLE_CLIENT_ID: "abc"
  GOOGLE_CLIENT_SECRET: "abc"
  GITHUB_ID: "abc"
  GITHUB_SECRET: "abc"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR